### PR TITLE
HackerRank Solution

### PR DESCRIPTION
**Pull request by aserputov**
Hey, @Rohit-554. 
I created this Pull Request with fixed source code but didn't finish my optimization yet. 
If you don't mind, now I want to try different algorithms.

Link to issue: #2 
Link to Task: https://www.hackerrank.com/challenges/repeated-string/problem

### CODE REVIEW

**Comment by aserputov** [comment]
First Test Results. 
Algorithm: 1. 
----------------
String: sakdjsjskajsakasjsdkdjasadkjsakdjksadjksjdlasjdlkjlasdjllasjdlajsdlkasjdklajlsdjlaksdjklasjdalkjdlaksjdlkaadsaaaa
Total a's : 24
Quantity: 5 000 000
Time spent with the first test: --- 3.814697265625e-06 seconds ---

**Comment by aserputov** [comment]
Second Test Results.
------------------
Algorithm: 1.
String: sakdjsjskajsakasjsdkdjasadkjsakdjksadjksjdlasjdlkjlasdjllasjdlajsdlkasjdklajlsdjlaksdjklasjdalkjdlaksjdlkaadsaaaa
Total a's : 24
Quantity: 5 000 000
Time spent with the first test: --- 1.6689300537109375e-06 seconds ---
---------------------------------
Increase in production: ~ 20x .

**Review by Rohit-554 — COMMENTED** [review]
I will be happy adding your code but your code doesn't giving the correct output , you can copy paste your code here https://www.hackerrank.com/challenges/repeated-string/problem
and run it ,  see the results ,
some changes are requried

**Comment by aserputov** [comment]
@Rohit-554 just a minute, I will check it there. Thank you for the link.

**Comment by aserputov** [comment]
@Rohit-554 True! I forgot the 10 letters limit, I will redo it now. Thank you !!

**Comment by aserputov** [comment]
@Rohit-554 Don
Screen Shot 2021-11-06 at 4 30 04 AM
e!
```
def repeatedString(s, n):
    count = 0
    if s.count('a') != len(s):
        length = ""
        for j in range(n):
            length = length + s
            if len(length) > 10:
                length = length[0:10]
                break

        print(length)

        for i in length:
            if i == 'a':
                count += 1
    else:
        count = len(s) * n

    print(count)

    result = count
    return result;    
```

**Review by Rohit-554 — COMMENTED** [review]
hackkerran

I appreciate Your Work but ... 
**Still cases failed**
You can take help from YouTube

**Comment by aserputov** [comment]
@Rohit-554 😂 no no no. I will finish this.

**Comment by aserputov** [comment]
I passed all the simple tests. Now, I need to work on speed.

**Comment by aserputov** [comment]
From ten tests to twenty-two @Rohit-554 :). One left

**Comment by aserputov** [comment]
Screen Shot 2021-11-07 at 12 34 51 AM
@Rohit-554 😀

**Review by Rohit-554 — APPROVED** [review]

**Review by Rohit-554 — COMMENTED** [review]
As You found the right code please give a single pr of this file i am deleting the older files

**Pull request closed without merging**
